/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import static School.ConnectDatabase.subjectTeacherDetails;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.NORMAL;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Kajamohan
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentPage
     */
    
    private String userName,password,classID;
    private final ConnectDatabase database = new ConnectDatabase();
    private int posX, posY;
    
    public StudentPage() throws SQLException {
        initComponents();
        initialSetting();
        setStaffsDetais();
        
    }
    
    private void initialSetting(){
        HeaderSetting h1 =  new HeaderSetting();
        h1.theader(TeacherTimetable.getTableHeader());  
        h1.HeaderRenderer(TeacherTimetable);
        
        HeaderSetting h2 =  new HeaderSetting();
        h2.theader(StaffsTable.getTableHeader());  
        h2.HeaderRenderer(StaffsTable);
       
        StaffsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setUserDetails(String UN, String PWD) throws SQLException{    
        userName = UN;
        password = PWD;        
        
        jScrollPane1.getVerticalScrollBar().setValue(0);
        
        String recivedValue [] = database.getStudentDetails(userName,"studenttab");
        
        IdTxt.setText(recivedValue[0]);
        TeacherPass.setText(password);
        
        NameTxt.setText(recivedValue[1]);
        userNameDisplay.setText(recivedValue[1]);
     
        GenTxt.setText(recivedValue[2]);
        DobTxt.setText(recivedValue[3]);
        AddmissionTxt.setText(recivedValue[4]);
        EmailTxt.setText(recivedValue[5]);
        MobileTxt.setText(recivedValue[6]);             
        AddressTxt.setText(recivedValue[7]);
        classID = recivedValue[8];
        classTxt.setText(database.StudentClassName);
       
        setTimeTable(classID);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameDisplay = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        TeacherMainPanel = new javax.swing.JTabbedPane();
        myAccScrollTab = new javax.swing.JScrollPane();
        myAccTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JLabel();
        MobileTxt = new javax.swing.JLabel();
        DobTxt = new javax.swing.JLabel();
        AddmissionTxt = new javax.swing.JLabel();
        classTxt = new javax.swing.JLabel();
        IdTxt = new javax.swing.JLabel();
        NameTxt = new javax.swing.JLabel();
        HideViewBtn = new javax.swing.JToggleButton();
        TeacherPass = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        GenTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        sclStaffTab = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        searchStaff = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        StaffsTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        subjectTab = new javax.swing.JPanel();
        ViewSubjectBtn = new javax.swing.JButton();
        ViewMarksBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        timetableTab = new javax.swing.JPanel();
        YearTerm = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TeacherTimetable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        reportTab = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ReportTxt = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        manageAccScrollTab = new javax.swing.JScrollPane();
        manageAccTab = new javax.swing.JPanel();
        HideViewBtn1 = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        CurrentPwd = new javax.swing.JPasswordField();
        UpdateBtn = new javax.swing.JButton();
        NewPwd = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        HideViewBtn2 = new javax.swing.JToggleButton();
        ConfirmPwd = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        HideViewBtn3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 8, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("School Management System");

        userNameDisplay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        userNameDisplay.setForeground(new java.awt.Color(0, 153, 153));
        userNameDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameDisplay.setText("Student Name");

        LogoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/School/Icons/logout.png"))); // NOI18N
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        TeacherMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TeacherMainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        TeacherMainPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TeacherMainPanel.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        TeacherMainPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        TeacherMainPanel.setOpaque(true);
        TeacherMainPanel.setPreferredSize(new java.awt.Dimension(1200, 897));

        myAccScrollTab.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));

        myAccTab.setBackground(new java.awt.Color(255, 255, 255));
        myAccTab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        myAccTab.setMaximumSize(new java.awt.Dimension(600, 820));
        myAccTab.setMinimumSize(new java.awt.Dimension(500, 700));
        myAccTab.setPreferredSize(new java.awt.Dimension(600, 775));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Your ID :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Your Password :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Email ID :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Mobile Number :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Date of Birth :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Addmission Date :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Class Name : ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Address :");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        EmailTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailTxt.setForeground(new java.awt.Color(153, 153, 153));

        MobileTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobileTxt.setForeground(new java.awt.Color(153, 153, 153));

        DobTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DobTxt.setForeground(new java.awt.Color(153, 153, 153));

        AddmissionTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddmissionTxt.setForeground(new java.awt.Color(153, 153, 153));

        classTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        classTxt.setForeground(new java.awt.Color(153, 153, 153));

        IdTxt.setBackground(new java.awt.Color(204, 255, 255));
        IdTxt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        IdTxt.setForeground(new java.awt.Color(153, 153, 153));
        IdTxt.setOpaque(true);

        NameTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameTxt.setForeground(new java.awt.Color(153, 153, 153));

        HideViewBtn.setForeground(new java.awt.Color(0, 204, 0));
        HideViewBtn.setIcon(new javax.swing.ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png")); // NOI18N
        HideViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideViewBtnActionPerformed(evt);
            }
        });

        TeacherPass.setEditable(false);
        TeacherPass.setBackground(new java.awt.Color(204, 255, 255));
        TeacherPass.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TeacherPass.setForeground(new java.awt.Color(153, 153, 153));
        TeacherPass.setBorder(null);
        TeacherPass.setDisabledTextColor(new java.awt.Color(204, 255, 255));
        TeacherPass.setFocusable(false);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Gender :");

        GenTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GenTxt.setForeground(new java.awt.Color(153, 153, 153));

        AddressTxt.setEditable(false);
        AddressTxt.setColumns(20);
        AddressTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddressTxt.setRows(5);
        AddressTxt.setTabSize(10);
        AddressTxt.setBorder(null);
        AddressTxt.setEnabled(false);
        AddressTxt.setFocusable(false);
        AddressTxt.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(AddressTxt);

        javax.swing.GroupLayout myAccTabLayout = new javax.swing.GroupLayout(myAccTab);
        myAccTab.setLayout(myAccTabLayout);
        myAccTabLayout.setHorizontalGroup(
            myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAccTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myAccTabLayout.createSequentialGroup()
                        .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddmissionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(myAccTabLayout.createSequentialGroup()
                                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TeacherPass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(HideViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(myAccTabLayout.createSequentialGroup()
                        .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GenTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        myAccTabLayout.setVerticalGroup(
            myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAccTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myAccTabLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myAccTabLayout.createSequentialGroup()
                        .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(myAccTabLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(HideViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myAccTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TeacherPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddmissionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(classTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        myAccScrollTab.setViewportView(myAccTab);

        TeacherMainPanel.addTab("My Account", myAccScrollTab);

        sclStaffTab.setBackground(new java.awt.Color(255, 255, 255));
        sclStaffTab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        sclStaffTab.setMaximumSize(new java.awt.Dimension(600, 600));
        sclStaffTab.setPreferredSize(new java.awt.Dimension(600, 420));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 204, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("School Staffs Details");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Search :");

        searchStaff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchStaffKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchStaffKeyReleased(evt);
            }
        });

        StaffsTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        StaffsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "Email", "Mobile"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StaffsTable.setRowHeight(40);
        StaffsTable.setShowGrid(true);
        StaffsTable.getTableHeader().setReorderingAllowed(false);
        StaffsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffsTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(StaffsTable);
        if (StaffsTable.getColumnModel().getColumnCount() > 0) {
            StaffsTable.getColumnModel().getColumn(0).setResizable(false);
            StaffsTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            StaffsTable.getColumnModel().getColumn(1).setResizable(false);
            StaffsTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            StaffsTable.getColumnModel().getColumn(2).setResizable(false);
            StaffsTable.getColumnModel().getColumn(2).setPreferredWidth(250);
            StaffsTable.getColumnModel().getColumn(3).setResizable(false);
            StaffsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        javax.swing.GroupLayout sclStaffTabLayout = new javax.swing.GroupLayout(sclStaffTab);
        sclStaffTab.setLayout(sclStaffTabLayout);
        sclStaffTabLayout.setHorizontalGroup(
            sclStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sclStaffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sclStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sclStaffTabLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sclStaffTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sclStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sclStaffTabLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sclStaffTabLayout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        sclStaffTabLayout.setVerticalGroup(
            sclStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sclStaffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sclStaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(sclStaffTab);

        TeacherMainPanel.addTab("School Staffs", jScrollPane2);

        subjectTab.setBackground(new java.awt.Color(255, 255, 255));
        subjectTab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        subjectTab.setMaximumSize(new java.awt.Dimension(614, 396));
        subjectTab.setPreferredSize(new java.awt.Dimension(614, 396));

        ViewSubjectBtn.setBackground(new java.awt.Color(0, 102, 102));
        ViewSubjectBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ViewSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewSubjectBtn.setText("View Subjects");
        ViewSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSubjectBtnActionPerformed(evt);
            }
        });

        ViewMarksBtn.setBackground(new java.awt.Color(0, 102, 102));
        ViewMarksBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ViewMarksBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewMarksBtn.setText("View Marks");
        ViewMarksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMarksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subjectTabLayout = new javax.swing.GroupLayout(subjectTab);
        subjectTab.setLayout(subjectTabLayout);
        subjectTabLayout.setHorizontalGroup(
            subjectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(subjectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewMarksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        subjectTabLayout.setVerticalGroup(
            subjectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectTabLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ViewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(ViewMarksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jScrollPane4.setViewportView(subjectTab);

        TeacherMainPanel.addTab("Subjects", jScrollPane4);

        timetableTab.setBackground(new java.awt.Color(255, 255, 255));
        timetableTab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        timetableTab.setMaximumSize(new java.awt.Dimension(960, 600));
        timetableTab.setPreferredSize(new java.awt.Dimension(960, 450));

        YearTerm.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        YearTerm.setForeground(new java.awt.Color(153, 153, 153));

        TeacherTimetable.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TeacherTimetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TeacherTimetable.setRowHeight(40);
        TeacherTimetable.setShowGrid(true);
        TeacherTimetable.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(TeacherTimetable);
        if (TeacherTimetable.getColumnModel().getColumnCount() > 0) {
            TeacherTimetable.getColumnModel().getColumn(0).setResizable(false);
            TeacherTimetable.getColumnModel().getColumn(1).setResizable(false);
            TeacherTimetable.getColumnModel().getColumn(2).setResizable(false);
            TeacherTimetable.getColumnModel().getColumn(3).setResizable(false);
            TeacherTimetable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout timetableTabLayout = new javax.swing.GroupLayout(timetableTab);
        timetableTab.setLayout(timetableTabLayout);
        timetableTabLayout.setHorizontalGroup(
            timetableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetableTabLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetableTabLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(YearTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        timetableTabLayout.setVerticalGroup(
            timetableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetableTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(YearTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        LocalDate Current = LocalDate.now();
        YearTerm.setText(Current.toString());

        jScrollPane5.setViewportView(timetableTab);

        TeacherMainPanel.addTab("Time Table", jScrollPane5);

        reportTab.setBackground(new java.awt.Color(255, 255, 255));
        reportTab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        reportTab.setMaximumSize(new java.awt.Dimension(600, 400));
        reportTab.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Report");

        ReportTxt.setColumns(20);
        ReportTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ReportTxt.setRows(5);
        jScrollPane8.setViewportView(ReportTxt);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Tell Your Problem :");

        SubmitBtn.setBackground(new java.awt.Color(0, 102, 102));
        SubmitBtn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(0, 102, 102));
        ClearBtn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportTabLayout = new javax.swing.GroupLayout(reportTab);
        reportTab.setLayout(reportTabLayout);
        reportTabLayout.setHorizontalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportTabLayout.createSequentialGroup()
                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportTabLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportTabLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reportTabLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reportTabLayout.createSequentialGroup()
                                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295)
                                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        reportTabLayout.setVerticalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(reportTab);

        TeacherMainPanel.addTab("Report", jScrollPane6);

        manageAccTab.setBackground(new java.awt.Color(255, 255, 255));
        manageAccTab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        manageAccTab.setMaximumSize(new java.awt.Dimension(610, 880));
        manageAccTab.setPreferredSize(new java.awt.Dimension(610, 340));

        HideViewBtn1.setForeground(new java.awt.Color(0, 204, 0));
        HideViewBtn1.setIcon(new javax.swing.ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png")); // NOI18N
        HideViewBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideViewBtn1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Current Password : ");

        CurrentPwd.setBackground(new java.awt.Color(204, 255, 255));
        CurrentPwd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CurrentPwd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CurrentPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CurrentPwdFocusLost(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(0, 102, 102));
        UpdateBtn.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Update");
        UpdateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        NewPwd.setBackground(new java.awt.Color(204, 255, 255));
        NewPwd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NewPwd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("New Password : ");

        HideViewBtn2.setForeground(new java.awt.Color(0, 204, 0));
        HideViewBtn2.setIcon(new javax.swing.ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png")); // NOI18N
        HideViewBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideViewBtn2ActionPerformed(evt);
            }
        });

        ConfirmPwd.setBackground(new java.awt.Color(204, 255, 255));
        ConfirmPwd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ConfirmPwd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Confirm Password : ");

        HideViewBtn3.setForeground(new java.awt.Color(0, 204, 0));
        HideViewBtn3.setIcon(new javax.swing.ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png")); // NOI18N
        HideViewBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideViewBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageAccTabLayout = new javax.swing.GroupLayout(manageAccTab);
        manageAccTab.setLayout(manageAccTabLayout);
        manageAccTabLayout.setHorizontalGroup(
            manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAccTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAccTabLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAccTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageAccTabLayout.createSequentialGroup()
                                .addComponent(CurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideViewBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAccTabLayout.createSequentialGroup()
                                .addComponent(NewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideViewBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAccTabLayout.createSequentialGroup()
                                .addComponent(ConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideViewBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        manageAccTabLayout.setVerticalGroup(
            manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAccTabLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAccTabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(HideViewBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAccTabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(HideViewBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAccTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAccTabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(HideViewBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        manageAccScrollTab.setViewportView(manageAccTab);

        TeacherMainPanel.addTab("Change Password", manageAccScrollTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(LogoutBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeacherMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220)
                                .addComponent(userNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // Get Mouse Position X,Y Co-Ordinates
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
         // Move all Frame using Mouse 
        setLocation(evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        this.dispose();
        LoginPage logout = new LoginPage();
        logout.setVisible(true);
        logout.initailsSetting("Logout Succesfully");
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        String s1,s2,s3;
        s1 = String.valueOf(CurrentPwd.getPassword());
        s2 = String.valueOf(NewPwd.getPassword());
        s3 = String.valueOf(ConfirmPwd.getPassword());
       
        boolean matchPass;
        
        if(!s1.equals(password)){
            CurrentPwd.setBackground(new java.awt.Color (204, 109, 112));
            CurrentPwd.setToolTipText("Your Current Password is Invalid!!");
            JOptionPane.showMessageDialog(this,"Your Current Password is Invalid!!");
            CurrentPwd.requestFocus();
            matchPass = false;
        }else if(!s2.equals(s3)){
            CurrentPwd.setBackground(new java.awt.Color(204,255,255));
            CurrentPwd.setToolTipText("Current Password");
            NewPwd.setBackground(new java.awt.Color(204, 109, 112));
            NewPwd.setToolTipText("Password Does not Matched!!");
            ConfirmPwd.setBackground(new java.awt.Color(204, 109, 112));
            ConfirmPwd.setToolTipText("Password Does not Matched!!");
            JOptionPane.showMessageDialog(this,"Password Does not Matched!!");
            NewPwd.requestFocus();
            matchPass = false;
        }else{
            CurrentPwd.setBackground(new java.awt.Color(204,255,255));
            CurrentPwd.setToolTipText("Current Password");
            NewPwd.setBackground(new java.awt.Color(204,255,255));
            NewPwd.setToolTipText("New Password");
            ConfirmPwd.setBackground(new java.awt.Color(204,255,255));
            ConfirmPwd.setToolTipText("Confirm Password");
            matchPass = true;
        }
       
        if(!s1.isBlank() && !s1.isEmpty() && !s2.isBlank() && !s2.isEmpty() && !s3.isBlank() && !s3.isEmpty() && matchPass){
                
            try {
                database.updateStudentPassword(userName, s2);
                setUserDetails(userName, s2);
                JOptionPane.showMessageDialog(this,"Your Details Update Successfully ");
                TeacherMainPanel.setSelectedIndex(0);
                CurrentPwd.setText("");
                NewPwd.setText("");
                ConfirmPwd.setText("");
                HideButtons();
                myAccScrollTab.getVerticalScrollBar().setValue(0);
            } catch (SQLException ex) {
                Logger.getLogger(StudentPage.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }else{
            JOptionPane.showMessageDialog(this,"Please Check your Inputs!!");
            
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void HideViewBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideViewBtn1ActionPerformed
       HideOrViewButtons();
    }//GEN-LAST:event_HideViewBtn1ActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        ReportTxt.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed

        if(!ReportTxt.getText().isBlank() || !ReportTxt.getText().isEmpty()  ){
            try {
                database.sendReport(IdTxt.getText(), ReportTxt.getText());
                ReportTxt.setText("");
                JOptionPane.showMessageDialog(this,"Reported Succesfully");
            } catch (SQLException ex) {
                Logger.getLogger(StudentPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                     
        }else{
            JOptionPane.showMessageDialog(this,"You didn't Enter your Problem");
            ReportTxt.requestFocus();
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void ViewMarksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMarksBtnActionPerformed
        setState(JFrame.ICONIFIED);
        try {
            ViewMarks studentMarks = new ViewMarks();
            studentMarks.setVisible(true);
            studentMarks.setTableHeaderValuesInStudent();
            studentMarks.setType('S');
            studentMarks.setClsID(classID);
            studentMarks.setStdID(userName);
            studentMarks.tableValuesForStudents();
        } catch (SQLException ex) {
            Logger.getLogger(StudentPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewMarksBtnActionPerformed

    private void ViewSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSubjectBtnActionPerformed
        setState(JFrame.ICONIFIED);
        try {
            displaySubjects(classID);
        } catch (SQLException ex) {
            Logger.getLogger(StudentPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ViewSubjectBtnActionPerformed

    private void HideViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideViewBtnActionPerformed
        HideOrViewButtons();
    }//GEN-LAST:event_HideViewBtnActionPerformed

    private void HideViewBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideViewBtn2ActionPerformed
       HideOrViewButtons();
    }//GEN-LAST:event_HideViewBtn2ActionPerformed

    private void HideViewBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideViewBtn3ActionPerformed
       HideOrViewButtons();
        
    }//GEN-LAST:event_HideViewBtn3ActionPerformed

    private void CurrentPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentPwdFocusLost
        String s1;
        s1 = String.valueOf(CurrentPwd.getPassword());
        if(!s1.equals(password)){
            CurrentPwd.setBackground(new java.awt.Color (204, 109, 112));
            CurrentPwd.setToolTipText("Your Current Password is Invalid!!");
            JOptionPane.showMessageDialog(this,"Your Current Password is Invalid!!");
            CurrentPwd.requestFocus();
            
        }else{
            CurrentPwd.setBackground(new java.awt.Color(204,255,255));
            CurrentPwd.setToolTipText("Current Password");
            NewPwd.setBackground(new java.awt.Color(204,255,255));
            NewPwd.setToolTipText("New Password");
            ConfirmPwd.setBackground(new java.awt.Color(204,255,255));
            ConfirmPwd.setToolTipText("Confirm Password");
        }
        
    }//GEN-LAST:event_CurrentPwdFocusLost

    private void searchStaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchStaffKeyPressed
       boolean check = false;
        int index = 0;
        
        DefaultTableModel StaffTableModel = (DefaultTableModel) StaffsTable.getModel();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            for(int i = 0; i<StaffsTable.getRowCount(); i++){
                if(StaffsTable.getModel().getValueAt(i,1).toString().toLowerCase().contains(searchStaff.getText().toLowerCase())){
                    check = true;
                    index = Integer.parseInt(StaffsTable.getModel().getValueAt(i, 0).toString());
                    break;
                }else
                    check = false;
            }
            
            
            int y = Integer.parseInt(StaffsTable.getModel().getValueAt(0, 0).toString());
           
            
            if(check  &&  y != index ){
                StaffsTable.addRowSelectionInterval(index-1,index-1 );
                StaffsTable.setSelectionBackground(Color.yellow);
                StaffsTable.setSelectionForeground(Color.black);
                int set = StaffsTable.getSelectedRow();
                StaffTableModel.moveRow(set,set, 0);
                StaffsTable.addRowSelectionInterval(0,0 );
                
            }else if(check){
                StaffsTable.addRowSelectionInterval(0,0 );
                StaffsTable.setSelectionBackground(Color.yellow);
                StaffsTable.setSelectionForeground(Color.black);
                
            }else{
                JOptionPane.showMessageDialog(this, "Results Not Found!!!","Not Found",NORMAL);
            }
        }
    }//GEN-LAST:event_searchStaffKeyPressed

    private void searchStaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchStaffKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK){
            
        }else{
            try {
                String textBoxString = searchStaff.getText();
                int textBoxStringLength = textBoxString.length();
                ConnectDatabase.addStaffs();

                for(Student data: ConnectDatabase.AllStaffsTable){
                    String  check_from_data = "";
                    
                    for(int i=0; i < textBoxStringLength; i++){
                        if(textBoxStringLength <= data.getName().length()){
                            check_from_data += data.getName().charAt(i);
                        }
                    }
                    if(check_from_data.toLowerCase().equals(textBoxString.toLowerCase()) || check_from_data.toUpperCase().equals(textBoxString.toUpperCase())){
                        searchStaff.setText(data.getName());
                        searchStaff.setSelectionStart(textBoxStringLength);
                        searchStaff.setSelectionEnd(data.getName().length());
                        break;
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchStaffKeyReleased

    private void StaffsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffsTableMouseClicked
        int selectedRow = StaffsTable.getSelectedRow();

        if(evt.getClickCount() == 1){
            searchStaff.setText(StaffsTable.getModel().getValueAt(selectedRow, 1).toString());
        }
    }//GEN-LAST:event_StaffsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StudentPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(StudentPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddmissionTxt;
    private javax.swing.JTextArea AddressTxt;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JPasswordField ConfirmPwd;
    private javax.swing.JPasswordField CurrentPwd;
    private javax.swing.JLabel DobTxt;
    private javax.swing.JLabel EmailTxt;
    private javax.swing.JLabel GenTxt;
    private javax.swing.JToggleButton HideViewBtn;
    private javax.swing.JToggleButton HideViewBtn1;
    private javax.swing.JToggleButton HideViewBtn2;
    private javax.swing.JToggleButton HideViewBtn3;
    private javax.swing.JLabel IdTxt;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JLabel MobileTxt;
    private javax.swing.JLabel NameTxt;
    private javax.swing.JPasswordField NewPwd;
    private javax.swing.JTextArea ReportTxt;
    private javax.swing.JTable StaffsTable;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTabbedPane TeacherMainPanel;
    private javax.swing.JPasswordField TeacherPass;
    private javax.swing.JTable TeacherTimetable;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton ViewMarksBtn;
    private javax.swing.JButton ViewSubjectBtn;
    private javax.swing.JLabel YearTerm;
    private javax.swing.JLabel classTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane manageAccScrollTab;
    private javax.swing.JPanel manageAccTab;
    private javax.swing.JScrollPane myAccScrollTab;
    private javax.swing.JPanel myAccTab;
    private javax.swing.JPanel reportTab;
    private javax.swing.JPanel sclStaffTab;
    private javax.swing.JTextField searchStaff;
    private javax.swing.JPanel subjectTab;
    private javax.swing.JPanel timetableTab;
    private javax.swing.JLabel userNameDisplay;
    // End of variables declaration//GEN-END:variables

    public void HideOrViewButtons(){
        Icon iconHide = new ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png");
        Icon iconView = new ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\view.png");
        
        // Hide or view Button 0
        if(HideViewBtn.getModel().isSelected()){
            TeacherPass.setEchoChar((char)0);
            HideViewBtn.setIcon(iconView);
        }else{
            TeacherPass.setEchoChar('*');
            HideViewBtn.setIcon(iconHide);
        }
        
        // Hide or view Button 1
        if(HideViewBtn1.getModel().isSelected()){
            CurrentPwd.setEchoChar((char)0);
            HideViewBtn1.setIcon(iconView);
        }else{
            CurrentPwd.setEchoChar('*');
            HideViewBtn1.setIcon(iconHide);
        }        
        
        // Hide or view Button 2
        if(HideViewBtn2.getModel().isSelected()){
            NewPwd.setEchoChar((char)0);
            HideViewBtn2.setIcon(iconView);
        }else{
            NewPwd.setEchoChar('*');
            HideViewBtn2.setIcon(iconHide);
        }
        
        // Hide or view Button 3
        if(HideViewBtn3.getModel().isSelected()){
            ConfirmPwd.setEchoChar((char)0);
            HideViewBtn3.setIcon(iconView);
        }else{
            ConfirmPwd.setEchoChar('*');
            HideViewBtn.setIcon(iconHide);
        }
        
    }
    
    public void HideButtons(){
        Icon iconHide = new ImageIcon("F:\\UINVERSITY OF JAFFNA NOTES\\5th Semester\\SQL Project\\SchoolManagementSystem\\src\\School\\Icons\\hide.png");
        HideViewBtn.setIcon(iconHide);
        HideViewBtn1.setIcon(iconHide);
        HideViewBtn2.setIcon(iconHide);
        HideViewBtn3.setIcon(iconHide);
    }
    
    
    /*
    *   Display Staffs Details in the School Staffs Tab
    */
    private void setStaffsDetais() throws SQLException{
        ConnectDatabase.AllStaffsTable.clear();
        ConnectDatabase.addStaffs();
        DefaultTableModel StaffTableModel = (DefaultTableModel) StaffsTable.getModel();
        
        int No;
        String Name , Email, Mobile;
            
        for(int i = 0; i<ConnectDatabase.AllStaffsTable.size(); i++){
            No = i+1;            
            Name = ConnectDatabase.AllStaffsTable.get(i).getName() ;            
            Email = ConnectDatabase.AllStaffsTable.get(i).getEmail() ;
            Mobile = ConnectDatabase.AllStaffsTable.get(i).getMobile() ;
            StaffTableModel.addRow(new Object[]{
                No,Name,Email,Mobile
            });
        }        
    }
    
        public void displaySubjects(String clsID) throws SQLException{
        
        Student.CalcuateTerm();
        int Y = Student.currentYear;
        int T = Student.currentTerm;
        
        ConnectDatabase.getSubjectAndTeacher(clsID,T,Y);
        
        if(subjectTeacherDetails.size() > 0){
            ViewStudentSubjects subject = new ViewStudentSubjects();
            subject.setVisible(true);
            subject.displaySubjects(classID);
            
        }else{
            JOptionPane.showMessageDialog(this,"Subjects Not Found!!","Not Found Message",NORMAL );
        }
        subjectTeacherDetails.clear();
        
    }
    
    public void setTimeTable(String cid) throws SQLException{
//            viewStudentTimeTable(String cID, String day, int period)
        String weekDays[] = {"Monday", "Tuesday","Wednesday","Thursday","Friday"};
        int colValue = TeacherTimetable.getColumnCount();
        int rowValue = TeacherTimetable.getRowCount();  
        String s;
        int period = 0;
        for(int i = 0; i< rowValue; i++){
            for(int j = 0; j< colValue; j++){
                period = i+1;
                s = ConnectDatabase.viewStudentTimeTable(cid,weekDays[j],period);
                TeacherTimetable.setValueAt(s, i, j);
            }
        }
    }
    
}
